tree_menu/menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='main_menu'),
    path('menu/<path:path>/', views.draw_menu, name='draw'),
]

tree_menu/tree_menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('menu.urls')),
    path('admin/', admin.site.urls),
]

tree_menu/menu/models.py
from django.db import models


class Menu(models.Model):
    name = models.CharField('Название', max_length=100, unique=True)

    class Meta:
        ordering = ('id',)
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'

    def __str__(self):
        return str(self.name)


class MenuPoint(models.Model):
    name = models.CharField('Название', max_length=100, unique=True)
    url = models.CharField('Ссылка', max_length=255, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='menu_point')

    class Meta:
        ordering = ('id',)
        verbose_name = 'Подпункты'
        verbose_name_plural = 'Подпункты'

    def __str__(self):
        return str(self.name)

tree_menu/menu/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Menu, MenuPoint


def index(request):
    return render(request, 'menu/index.html', {'menus': Menu.objects.all()})


def draw_menu(request, path):
    splitted_path = path.split('/')
    print(splitted_path)
    if len(splitted_path)>1:
        point_path = splitted_path[-1]
        print(point_path)
        point = MenuPoint.objects.filter(parent=point_path)
        # point_chek = MenuPoint.objects.in_bulk()
        # for x in point_chek:
        #     print(x)
        print(point)
        # print(point_chek[11])
        print('pizda')
        context = {
        'point': point,
    }
        return render(request, 'menu/menu.html', context)
    # else:
    #     people2 = MenuPoint.objects.in_bulk()
    #     for id in people2:
    #         print(people2[id].parent)
        # return render(request, 'menu/menu.html', {'point':people2,})
    else:
        str_obj = ''.join(splitted_path)
        print('url: ', str_obj)
        menu_obj = Menu.objects.get(name=str_obj)
        id_menu = menu_obj.id
        print('id_menu: ', id_menu)
        point = MenuPoint.objects.filter(menu=id_menu, parent=None)
        print('point: ', point)
        context = {
            'point': point,
        }
        return render(request, 'menu/menu.html', context)

tree_menu/menu/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">          
  <head>
    {% block title %}
      <title> hello </title>
    {% endblock title %}
  </head>
  <body>
    
    <header>

    </header>
    <main>
      {% block content %}
        Контент не подвезли :(
      {% endblock content %}
    </main>
    <footer>

    </footer>
  </body>
</html>

tree_menu/menu/templates/menu/index.html
{% comment %} {% load show_menu %} {% endcomment %}

{% if menus %}
    <ul>
        {% for menu in menus %}
            <li><a href={% url 'menu:draw' menu.name %}>{{ menu.name }}</li>
        {% endfor %}
    </ul>    
{% comment %} {% elif menu_name %} {% endcomment %}
    {% comment %} <h3><a href={% url 'menu:main_menu' %}>В главное меню</h3> {% endcomment %}
    
{% endif %}
{% comment %} {% draw_menu menu_name menu_item %} {% endcomment %}

tree_menu/menu/templates/menu/menu.html
{% extends 'base.html' %}
{% comment %} <ul>
    {% for item in point %}
        {% if item.url %}<li><a href='{{ item.url }}'>{{ item }}</li>
        {% elif item.name %}<li><a href='{{ item.name }}'>{{ item }}</li>
        {% else %}{% include 'menu/menu.html' with menu=item %}
        {% endif %}
    {% endfor %}
    <h3><a href={% url 'menu:main_menu' %}>В главное меню</h3>
</ul> {% endcomment %}
{% comment %} {% load show_menu %}
<ul>
    {% for child in point %}
    <li> <a href="{{ child.url }}">{{ child }}</a></li>
        {% if child.children.count > 0 %}
        {% show_menu child %}
        {% endif %}
    {% endfor %}
    <h3><a href={% url 'menu:main_menu' %}>В главное меню</h3>
</ul> {% endcomment %}

{% block content %}
{% load show_menu %}
<ul>
{% for person in point %}
  <li> <a href="{{ person.id }}">{{ person }}</a> {% show_menu person %}</li>
  {% comment %} {% show_menu 'main_menu' %} {% endcomment %}
{% endfor %}</ul>
{% endblock %}
<h3><a href={% url 'menu:main_menu' %}>В главное меню</h3>